
services:
  aziz.content.builder.content:
    class: Aziz\ContentBuilderBundle\EventListener\Content
    public: true
    arguments:
      - "@router"
      - "@contao.security.token_checker"
    tags:
      - { name: contao.hook, hook: getContentElement }

  aziz.content.builder.system:
    class: Aziz\ContentBuilderBundle\EventListener\System
    public: true
    tags:
      - { name: contao.hook, hook: initializeSystem }
